
OBJS_BULLET = ./BulletCollision/BroadphaseCollision/btAxisSweep3.o \
		./BulletCollision/BroadphaseCollision/btBroadphaseProxy.o \
		./BulletCollision/BroadphaseCollision/btCollisionAlgorithm.o \
		./BulletCollision/BroadphaseCollision/btDbvt.o \
		./BulletCollision/BroadphaseCollision/btDbvtBroadphase.o \
		./BulletCollision/BroadphaseCollision/btDispatcher.o \
		./BulletCollision/BroadphaseCollision/btMultiSapBroadphase.o \
		./BulletCollision/BroadphaseCollision/btOverlappingPairCache.o \
		./BulletCollision/BroadphaseCollision/btQuantizedBvh.o \
		./BulletCollision/BroadphaseCollision/btSimpleBroadphase.o \
		./BulletCollision/CollisionDispatch/btActivatingCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btBox2dBox2dCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btBoxBoxCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btBoxBoxDetector.o \
		./BulletCollision/CollisionDispatch/btCollisionDispatcher.o \
		./BulletCollision/CollisionDispatch/btCollisionObject.o \
		./BulletCollision/CollisionDispatch/btCollisionWorld.o \
		./BulletCollision/CollisionDispatch/btCompoundCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btCompoundCompoundCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btConvex2dConvex2dAlgorithm.o \
		./BulletCollision/CollisionDispatch/btConvexConcaveCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btConvexConvexAlgorithm.o \
		./BulletCollision/CollisionDispatch/btConvexPlaneCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btDefaultCollisionConfiguration.o \
		./BulletCollision/CollisionDispatch/btEmptyCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btGhostObject.o \
		./BulletCollision/CollisionDispatch/btHashedSimplePairCache.o \
		./BulletCollision/CollisionDispatch/btInternalEdgeUtility.o \
		./BulletCollision/CollisionDispatch/btManifoldResult.o \
		./BulletCollision/CollisionDispatch/btSimulationIslandManager.o \
		./BulletCollision/CollisionDispatch/btSphereBoxCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btSphereSphereCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btSphereTriangleCollisionAlgorithm.o \
		./BulletCollision/CollisionDispatch/btUnionFind.o \
		./BulletCollision/CollisionDispatch/SphereTriangleDetector.o \
		./BulletCollision/CollisionShapes/btBox2dShape.o \
		./BulletCollision/CollisionShapes/btBoxShape.o \
		./BulletCollision/CollisionShapes/btBvhTriangleMeshShape.o \
		./BulletCollision/CollisionShapes/btCapsuleShape.o \
		./BulletCollision/CollisionShapes/btCollisionShape.o \
		./BulletCollision/CollisionShapes/btCompoundShape.o \
		./BulletCollision/CollisionShapes/btConcaveShape.o \
		./BulletCollision/CollisionShapes/btConeShape.o \
		./BulletCollision/CollisionShapes/btConvex2dShape.o \
		./BulletCollision/CollisionShapes/btConvexHullShape.o \
		./BulletCollision/CollisionShapes/btConvexInternalShape.o \
		./BulletCollision/CollisionShapes/btConvexPointCloudShape.o \
		./BulletCollision/CollisionShapes/btConvexPolyhedron.o \
		./BulletCollision/CollisionShapes/btConvexShape.o \
		./BulletCollision/CollisionShapes/btConvexTriangleMeshShape.o \
		./BulletCollision/CollisionShapes/btCylinderShape.o \
		./BulletCollision/CollisionShapes/btEmptyShape.o \
		./BulletCollision/CollisionShapes/btHeightfieldTerrainShape.o \
		./BulletCollision/CollisionShapes/btMinkowskiSumShape.o \
		./BulletCollision/CollisionShapes/btMultimaterialTriangleMeshShape.o \
		./BulletCollision/CollisionShapes/btMultiSphereShape.o \
		./BulletCollision/CollisionShapes/btOptimizedBvh.o \
		./BulletCollision/CollisionShapes/btPolyhedralConvexShape.o \
		./BulletCollision/CollisionShapes/btScaledBvhTriangleMeshShape.o \
		./BulletCollision/CollisionShapes/btShapeHull.o \
		./BulletCollision/CollisionShapes/btSphereShape.o \
		./BulletCollision/CollisionShapes/btStaticPlaneShape.o \
		./BulletCollision/CollisionShapes/btStridingMeshInterface.o \
		./BulletCollision/CollisionShapes/btTetrahedronShape.o \
		./BulletCollision/CollisionShapes/btTriangleBuffer.o \
		./BulletCollision/CollisionShapes/btTriangleCallback.o \
		./BulletCollision/CollisionShapes/btTriangleIndexVertexArray.o \
		./BulletCollision/CollisionShapes/btTriangleIndexVertexMaterialArray.o \
		./BulletCollision/CollisionShapes/btTriangleMesh.o \
		./BulletCollision/CollisionShapes/btTriangleMeshShape.o \
		./BulletCollision/CollisionShapes/btUniformScalingShape.o \
		./BulletCollision/Gimpact/btContactProcessing.o \
		./BulletCollision/Gimpact/btGenericPoolAllocator.o \
		./BulletCollision/Gimpact/btGImpactBvh.o \
		./BulletCollision/Gimpact/btGImpactCollisionAlgorithm.o \
		./BulletCollision/Gimpact/btGImpactQuantizedBvh.o \
		./BulletCollision/Gimpact/btGImpactShape.o \
		./BulletCollision/Gimpact/btTriangleShapeEx.o \
		./BulletCollision/Gimpact/gim_box_set.o \
		./BulletCollision/Gimpact/gim_contact.o \
		./BulletCollision/Gimpact/gim_memory.o \
		./BulletCollision/Gimpact/gim_tri_collision.o \
		./BulletCollision/NarrowPhaseCollision/btContinuousConvexCollision.o \
		./BulletCollision/NarrowPhaseCollision/btConvexCast.o \
		./BulletCollision/NarrowPhaseCollision/btGjkConvexCast.o \
		./BulletCollision/NarrowPhaseCollision/btGjkEpa2.o \
		./BulletCollision/NarrowPhaseCollision/btGjkEpaPenetrationDepthSolver.o \
		./BulletCollision/NarrowPhaseCollision/btGjkPairDetector.o \
		./BulletCollision/NarrowPhaseCollision/btMinkowskiPenetrationDepthSolver.o \
		./BulletCollision/NarrowPhaseCollision/btPersistentManifold.o \
		./BulletCollision/NarrowPhaseCollision/btPolyhedralContactClipping.o \
		./BulletCollision/NarrowPhaseCollision/btRaycastCallback.o \
		./BulletCollision/NarrowPhaseCollision/btSubSimplexConvexCast.o \
		./BulletCollision/NarrowPhaseCollision/btVoronoiSimplexSolver.o \
		./BulletDynamics/Character/btKinematicCharacterController.o \
		./BulletDynamics/ConstraintSolver/btConeTwistConstraint.o \
		./BulletDynamics/ConstraintSolver/btContactConstraint.o \
		./BulletDynamics/ConstraintSolver/btFixedConstraint.o \
		./BulletDynamics/ConstraintSolver/btGearConstraint.o \
		./BulletDynamics/ConstraintSolver/btGeneric6DofConstraint.o \
		./BulletDynamics/ConstraintSolver/btGeneric6DofSpringConstraint.o \
		./BulletDynamics/ConstraintSolver/btHinge2Constraint.o \
		./BulletDynamics/ConstraintSolver/btHingeConstraint.o \
		./BulletDynamics/ConstraintSolver/btNNCGConstraintSolver.o \
		./BulletDynamics/ConstraintSolver/btPoint2PointConstraint.o \
		./BulletDynamics/ConstraintSolver/btSequentialImpulseConstraintSolver.o \
		./BulletDynamics/ConstraintSolver/btSliderConstraint.o \
		./BulletDynamics/ConstraintSolver/btSolve2LinearConstraint.o \
		./BulletDynamics/ConstraintSolver/btTypedConstraint.o \
		./BulletDynamics/ConstraintSolver/btUniversalConstraint.o \
		./BulletDynamics/Dynamics/btDiscreteDynamicsWorld.o \
		./BulletDynamics/Dynamics/btRigidBody.o \
		./BulletDynamics/Dynamics/btSimpleDynamicsWorld.o \
		./BulletDynamics/Featherstone/btMultiBody.o \
		./BulletDynamics/Featherstone/btMultiBodyConstraint.o \
		./BulletDynamics/Featherstone/btMultiBodyConstraintSolver.o \
		./BulletDynamics/Featherstone/btMultiBodyDynamicsWorld.o \
		./BulletDynamics/Featherstone/btMultiBodyJointLimitConstraint.o \
		./BulletDynamics/Featherstone/btMultiBodyJointMotor.o \
		./BulletDynamics/Featherstone/btMultiBodyPoint2Point.o \
		./BulletDynamics/MLCPSolvers/btDantzigLCP.o \
		./BulletDynamics/MLCPSolvers/btLemkeAlgorithm.o \
		./BulletDynamics/MLCPSolvers/btMLCPSolver.o \
		./BulletDynamics/Vehicle/btRaycastVehicle.o \
		./BulletDynamics/Vehicle/btWheelInfo.o \
		./BulletSoftBody/btDefaultSoftBodySolver.o \
		./BulletSoftBody/btSoftBody.o \
		./BulletSoftBody/btSoftBodyConcaveCollisionAlgorithm.o \
		./BulletSoftBody/btSoftBodyHelpers.o \
		./BulletSoftBody/btSoftBodyRigidBodyCollisionConfiguration.o \
		./BulletSoftBody/btSoftRigidCollisionAlgorithm.o \
		./BulletSoftBody/btSoftRigidDynamicsWorld.o \
		./BulletSoftBody/btSoftSoftCollisionAlgorithm.o \
		./LinearMath/btAlignedAllocator.o \
		./LinearMath/btConvexHull.o \
		./LinearMath/btConvexHullComputer.o \
		./LinearMath/btGeometryUtil.o \
		./LinearMath/btPolarDecomposition.o \
		./LinearMath/btQuickprof.o \
		./LinearMath/btSerializer.o \
		./LinearMath/btVector3.o \
 


CC = gcc
CXX = g++
CXXFLAGS = -O3 -fPIC
INCDIRS = .

src =$(OBJS_BULLET)

obj = $(src:.cpp=.o)
INC_PARAMS=$(foreach d, $(INCDIRS), -I$d)
CXXFLAGS += $(INC_PARAMS)

INCLIBS_PARAMS=$(foreach d, $(LIBDIRS), -L$d)
LDFLAGS += $(INCLIBS_PARAMS)

../build/libbullet.a: $(obj)
	ar rcs $@ $^ 

.PHONY: clean


clean: 
	rm -f $(src) ../build/libbullet.a